config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("musicreview.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'Songs/',
        include('musicreview.Songs.urls',
                namespace='Songs')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

musicreview/Songs/urls.py
from django.urls import path
from . import views

app_name = "Songs"
urlpatterns = [
    path('spotify-auth-redirect/', views.spotify_auth_redirect, name='spotify-auth-redirect'),
    path('spotify-callback/', views.spotify_callback, name='spotify-callback'),
    path('save/', views.save_song, name='save'),
    path('review/<int:pk>', views.ReviewView.as_view(), name='song-review'),
    path(
        route='',
        view=views.SongListView.as_view(),
        name='list'
    ),
    path(
        route='create/',
        view=views.SongCreateView.as_view(),
        name='create'
    ),
    path(
        route='detail/<int:pk>/',
        view=views.SongDetailView.as_view(),
        name='detail'
    ),
    path(
        route='delete/<int:pk>/',
        view=views.SongDeleteView.as_view(),
        name='delete'
    ),
    path('api/<int:pk>/reviews/', views.song_reviews, name='song-reviews'),
    #edit review
    path('edit-review/<int:pk>', views.EditReviewView.as_view(), name='edit-review'),
    #confirm delete review
    path('delete-review/<int:pk>', views.DeleteReviewView.as_view(), name='delete-review'),
    #delete review
    path('delete-review/confirmed/<int:pk>', views.delete_review, name='delete-review-confirmed'),
    #get all reviews for a given user pk
    path('api/user/<int:pk>/reviews/', views.user_reviews, name='user-reviews'),
    #get spotify song id from song id
    path('api/song/<int:pk>/spotify-id/', views.get_spotify_song_id, name='get-spotify-song-id'),

]

musicreview/users/urls.py
from django.urls import path

from musicreview.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

musicreview/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )
    bio = models.TextField("Bio", blank=True)
    
    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

musicreview/Songs/forms.py
from django import forms
from .models import SongRating

class SongRatingForm(forms.ModelForm):
    rating = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 6)],  # Choices from 1 to 5
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = SongRating
        fields = ['rating', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

class EditReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 6)],  # Choices from 1 to 5
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    class Meta:
        model = SongRating
        fields = ['rating', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

musicreview/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

musicreview/Songs/views.py
# Standard library imports
from urllib.parse import urlencode, urljoin
import json
import requests

# Django imports
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.http import is_safe_url
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import (
    ListView, DetailView, DeleteView, CreateView, UpdateView, FormView, TemplateView
)

# Local imports from the current application
from .models import Song, SongRating
from .forms import SongRatingForm, EditReviewForm


class SongListView(ListView):
    model = Song

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        songs = Song.objects.values('id', 'spotify_song_id')

        # Enhance song data with user's review status if the user is logged in
        if self.request.user.is_authenticated:
            enhanced_songs = []
            for song in songs:
                song_id = song['id']
                user_has_reviewed = SongRating.objects.filter(Song_id=song_id, creator=self.request.user).exists()
                enhanced_song = song.copy()
                enhanced_song['user_has_reviewed'] = str(user_has_reviewed)
                enhanced_songs.append(enhanced_song)

            #associate the average rating with each song
            for song in enhanced_songs:
                song_id = song['id']
                song_obj = Song.objects.get(id=song_id)
                song['average_rating'] = song_obj.average_rating()

            context['songs'] = enhanced_songs
        else:
            songs = Song.objects.values('id', 'spotify_song_id')
            songs = list(songs)
            #associate the average rating with each song
            for song in songs:
                song_id = song['id']
                song_obj = Song.objects.get(id=song_id)
                song['average_rating'] = song_obj.average_rating()
            context['songs'] = list(songs)
        return context


class SongDetailView(DetailView):
    model = Song

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Add the Spotify song ID to the context
        spotify_song_id = self.object.spotify_song_id
        context['spotify_song_id'] = spotify_song_id


        return context
    
class ReviewView(LoginRequiredMixin, FormView):
    template_name = 'songs/song_rate_view.html'
    form_class = SongRatingForm

    def form_valid(self, form):
        song_rating = form.save(commit=False)
        song_rating.creator = self.request.user
        song_id = self.kwargs.get('pk')
        song_rating.Song = Song.objects.get(pk=song_id)
        song_rating.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Redirect after a successful submission
        return reverse('Songs:detail', kwargs={'pk': self.kwargs['pk']})

class EditReviewView(LoginRequiredMixin, UpdateView):
    model = SongRating
    template_name = 'songs/song_rate_view.html'
    form_class = EditReviewForm

    def get_success_url(self):
        # Redirect after a successful submission
        return reverse('Songs:detail', kwargs={'pk': self.object.Song_id})

    def get_object(self, queryset=None):
        # Only get the SongRating object for the current user and song
        # if multiple (shouldn't be but just in case) then get the first one
        obj = SongRating.objects.filter(Song_id=self.kwargs['pk'], creator=self.request.user).first()
        return obj
    
    #context for auto populating the form rating and comment
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rating'] = self.object.rating
        context['comment'] = self.object.comment
        return context
    
class DeleteReviewView(LoginRequiredMixin, DeleteView):
    model = SongRating
    template_name = 'songs/song_delete_review.html'

    def get_success_url(self):
        # Redirect after a successful submission
        return reverse('Songs:detail', kwargs={'pk': self.object.Song_id})

    def get_object(self, queryset=None):
        # Only get the SongRating object for the current user and song
        # if multiple (shouldn't be but just in case) then get the first one
        obj = SongRating.objects.filter(Song_id=self.kwargs['pk'], creator=self.request.user).first()
        return obj
    
def delete_review(request, pk):
    review = SongRating.objects.get(id=pk)
    if request.method == "POST":
        review.delete()
        return redirect('Songs:detail', pk=review.Song_id)
    context = {'review': review}
    return render(request, 'songs/song_delete_review.html', context)

class SongDeleteView(UserPassesTestMixin, DeleteView):
    model = Song
    success_url = reverse_lazy('Songs:list')

    def test_func(self):
        return self.request.user.is_superuser

class SongCreateView(CreateView):
    model = Song
    fields = ['spotify_song_id']
    template_name = 'Songs/Song_create_view.html'
    success_url = reverse_lazy('Songs:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['spotify_access_token'] = self.request.session.get('spotify_access_token', '')
        return context

def song_reviews(request, pk):
    reviews_query = SongRating.objects.filter(Song_id=pk).values(
        'id', 'rating', 'comment', 'creator__username', 'Song'
    )

    reviews = list(reviews_query)
    if request.user.is_authenticated:
        user_review = next((r for r in reviews if r['creator__username'] == request.user.username), None)
        if user_review:
            reviews.remove(user_review)
            reviews.insert(0, user_review)

    return JsonResponse(reviews, safe=False)

def user_reviews(request, pk):
    reviews_query = SongRating.objects.filter(creator_id=pk).values(
        'id', 'rating', 'comment', 'creator__username', 'Song'
    )

    reviews = list(reviews_query)
    if request.user.is_authenticated:
        user_review = next((r for r in reviews if r['creator__username'] == request.user.username), None)
        if user_review:
            reviews.remove(user_review)
            reviews.insert(0, user_review)

    return JsonResponse(reviews, safe=False)

def get_spotify_song_id(request, pk):
    song = Song.objects.get(id=pk)
    spotify_song_id = song.spotify_song_id
    return JsonResponse({'spotify_song_id': spotify_song_id})

def spotify_auth_redirect(request):
    next_url = request.GET.get('next', settings.DEFAULT_RETURN_URL)
    #prepend "Songs:" to the next_url
    next_url = "Songs:" + next_url
    full_next_url = request.build_absolute_uri(reverse(next_url))

    params = {
        'client_id': settings.SPOTIFY_CLIENT_ID,
        'response_type': 'code',
        'redirect_uri': settings.SPOTIFY_REDIRECT_URI,
        'scope': 'user-read-private',
        'state': next_url,  # Use state parameter to pass the next_url
    }
    url = f'https://accounts.spotify.com/authorize?{urlencode(params)}'
    return redirect(url)

def spotify_callback(request):
    code = request.GET.get('code')
    error = request.GET.get('error')
    next_url = request.GET.get('state', settings.DEFAULT_RETURN_URL)
    #next_url = "Songs:" + next_url

    if error:
        # Handle the scenario where the user denied the request or some other error occurred.
        return HttpResponseRedirect(reverse('error_view_name'))  # Redirect to an error page or similar.

    if code:
        # Exchange the code for an access token
        response = requests.post('https://accounts.spotify.com/api/token', data={
            'grant_type': 'authorization_code',
            'code': code,
            'redirect_uri': settings.SPOTIFY_REDIRECT_URI,
            'client_id': settings.SPOTIFY_CLIENT_ID,
            'client_secret': settings.SPOTIFY_CLIENT_SECRET,
        })

        if response.status_code == 200:
            data = response.json()
            access_token = data['access_token']
            # Optionally handle refresh_token and save them for later use.
            request.session['spotify_access_token'] = access_token  # Save the access token in the session or user's profile

            # Ensure the next_url is safe to redirect to
            #if not is_safe_url(url=next_url, allowed_hosts={request.get_host()}):
            #    return HttpResponseRedirect(reverse('Songs:list'))  # Redirect to a safe default page

            return HttpResponseRedirect(reverse(next_url))
        else:
            # Handle failure in obtaining an access token.
            return HttpResponseRedirect(reverse('error_view_name'))  # Redirect to an error page or similar.

    # Handle scenarios where there's neither code nor error.
    return HttpResponseRedirect(reverse('default_view_name'))  # Redirect to a default page or an error page.

@csrf_exempt  # Consider using CSRF protection for production
@require_POST
def save_song(request):
    data = json.loads(request.body)
    spotify_song_id = data.get('spotify_song_id')

    if spotify_song_id:
        # Create and save the new song
        song = Song(spotify_song_id=spotify_song_id)
        song.save()
        return JsonResponse({'status': 'success', 'message': 'Song added successfully'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid data'}, status=400)

musicreview/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_id'] = self.object.id  # Add the user's ID to the context
        return context



user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
        "bio"
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

musicreview/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
      {% if object.bio %}
      <p>{{ object.bio }}</p>
      {% endif %}
    </div>
    
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

  <!-- Reviews Section -->
  <div class="row">
      <div class="col-sm-12">
          <h3>User Reviews</h3>
          <div id="reviews-container">
              <!-- Reviews will be loaded here -->
          </div>
      </div>
  </div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
  $(document).ready(function() {
      const accessToken = '{{ request.session.spotify_access_token }}'; // Ensure this is available in your template

      function fetchUserReviews() {
          const userId = {{ object.id }};
          $.ajax({
              url: `/Songs/api/user/${userId}/reviews/`,
              type: 'GET',
              success: function(reviews) {
                  displayReviews(reviews);
              },
              error: function(error) {
                  console.error('Error fetching reviews:', error);
              }
          });
      }

      function fetchSongName(spotifySongId) {
          return $.ajax({
              url: `https://api.spotify.com/v1/tracks/${spotifySongId}`,
              type: 'GET',
              headers: {
                  'Authorization': `Bearer ${accessToken}`
              },
              success: function(songData) {
                  return songData.name;
              },
              error: function(error) {
                  console.error('Error fetching song data:', error);
                  return 'Unknown Song';
              }
          });
      }

      function getSpotifyId(songId) {
          return $.ajax({
              url: `/Songs/api/song/${songId}/spotify-id/`,
              type: 'GET',
              success: function(songData) {
                  return songData['spotify_song_id'];
              },
              error: function(error) {
                  console.error('Error fetching song data:', error);
                  return null;
              }
          });
      }

      function getSpotifyArtistName(songId) {
          return $.ajax({
              url: `https://api.spotify.com/v1/tracks/${songId}`,
              type: 'GET',
              headers: {
                  'Authorization': `Bearer ${accessToken}`
              },
              success: function(spotifySongData) {
                  return spotifySongData.artists[0].name;
              },
              error: function(error) {
                  console.error('Error:', error);
                  return null;
              }
          });
      }

      const currentUser = "{{ request.user.username }}" || null;
      async function displayReviews(reviews) {
          let reviewsSection = $('#reviews-container');
          for (const review of reviews) {
            console.log(review);
            let spotifyId = await getSpotifyId(review.Song);
            spotifyId = spotifyId['spotify_song_id'];
            let songName = await fetchSongName(spotifyId); // Assuming review object has spotify_song_id
            let artistName = await getSpotifyArtistName(spotifyId); // Assuming review object has spotify_song_id
            let isUserReview = currentUser && review.creator__username === currentUser;
            
            songName = songName['name']
            artistName = artistName['artists'][0]['name']
            console.log(spotifyId)
            console.log(songName)
            console.log(artistName)
            let reviewCard = $('<div>').addClass('card mb-2');
            reviewCard.html(`
                <div class="card-body">
                    <h5 class="card-title">${songName} - ${artistName}</h5>
                    <p class="card-text"><strong>Review by:</strong> ${review.creator__username}</p>
                    <p class="card-text">${review.comment}</p>
                    <p class="card-text">Rating: ${'★'.repeat(review.rating)}</p>
                    ${isUserReview ? `<button onclick="editReview(${review.Song})">Edit Review</button>` : ''}
                    ${isUserReview ? `<button onclick="deleteReview(${review.Song})">Delete Review</button>` : ''}
                </div>
            `);
            reviewsSection.append(reviewCard);
          }
      }

      fetchUserReviews();
  });
</script>



{% endblock content %}

musicreview/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}