config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("musicreview.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        'Songs/',
        include('musicreview.Songs.urls',
                namespace='Songs')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

musicreview/Songs/urls.py
from django.urls import path
from . import views

app_name = "Songs"
urlpatterns = [
    path('spotify-auth-redirect/', views.spotify_auth_redirect, name='spotify-auth-redirect'),
    path('spotify-callback/', views.spotify_callback, name='spotify-callback'),
    path('save/', views.save_song, name='save'),
    path('review/<int:pk>', views.ReviewView.as_view(), name='song-review'),
    path(
        route='',
        view=views.SongListView.as_view(),
        name='list'
    ),
    path(
        route='create/',
        view=views.SongCreateView.as_view(),
        name='create'
    ),
    path(
        route='detail/<int:pk>/',
        view=views.SongDetailView.as_view(),
        name='detail'
    ),
    path(
        route='delete/<int:pk>/',
        view=views.SongDeleteView.as_view(),
        name='delete'
    ),
    path('api/<int:pk>/reviews/', views.song_reviews, name='song-reviews'),
    #edit review
    path('edit-review/<int:pk>', views.EditReviewView.as_view(), name='edit-review'),
    #confirm delete review
    path('delete-review/<int:pk>', views.DeleteReviewView.as_view(), name='delete-review'),
    #delete review
    path('delete-review/confirmed/<int:pk>', views.delete_review, name='delete-review-confirmed'),
    #get all reviews for a given user pk
    path('api/user/<int:pk>/reviews/', views.user_reviews, name='user-reviews'),
    #get spotify song id from song id
    path('api/song/<int:pk>/spotify-id/', views.get_spotify_song_id, name='get-spotify-song-id'),

]

musicreview/users/urls.py
from django.urls import path

from musicreview.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

musicreview/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )
    bio = models.TextField("Bio", blank=True)
    
    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

musicreview/Songs/forms.py
from django import forms
from .models import SongRating

class SongRatingForm(forms.ModelForm):
    rating = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 6)],  # Choices from 1 to 5
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = SongRating
        fields = ['rating', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

class EditReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(
        choices=[(i, str(i)) for i in range(1, 6)],  # Choices from 1 to 5
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    class Meta:
        model = SongRating
        fields = ['rating', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

musicreview/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

musicreview/Songs/views.py
# Standard library imports
from urllib.parse import urlencode, urljoin
import json
import requests

# Django imports
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.http import is_safe_url
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import (
    ListView, DetailView, DeleteView, CreateView, UpdateView, FormView, TemplateView
)

# Local imports from the current application
from .models import Song, SongRating
from .forms import SongRatingForm, EditReviewForm


class SongListView(ListView):
    model = Song

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        songs = Song.objects.values('id', 'spotify_song_id')

        # Enhance song data with user's review status if the user is logged in
        if self.request.user.is_authenticated:
            enhanced_songs = []
            for song in songs:
                song_id = song['id']
                user_has_reviewed = SongRating.objects.filter(Song_id=song_id, creator=self.request.user).exists()
                enhanced_song = song.copy()
                enhanced_song['user_has_reviewed'] = str(user_has_reviewed)
                enhanced_songs.append(enhanced_song)

            #associate the average rating with each song
            for song in enhanced_songs:
                song_id = song['id']
                song_obj = Song.objects.get(id=song_id)
                song['average_rating'] = song_obj.average_rating()

            context['songs'] = enhanced_songs
        else:
            songs = Song.objects.values('id', 'spotify_song_id')
            songs = list(songs)
            #associate the average rating with each song
            for song in songs:
                song_id = song['id']
                song_obj = Song.objects.get(id=song_id)
                song['average_rating'] = song_obj.average_rating()
            context['songs'] = list(songs)
        return context


class SongDetailView(DetailView):
    model = Song

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Add the Spotify song ID to the context
        spotify_song_id = self.object.spotify_song_id
        context['spotify_song_id'] = spotify_song_id


        return context
    
class ReviewView(LoginRequiredMixin, FormView):
    template_name = 'songs/song_rate_view.html'
    form_class = SongRatingForm

    def form_valid(self, form):
        song_rating = form.save(commit=False)
        song_rating.creator = self.request.user
        song_id = self.kwargs.get('pk')
        song_rating.Song = Song.objects.get(pk=song_id)
        song_rating.save()
        return super().form_valid(form)

    def get_success_url(self):
        # Redirect after a successful submission
        return reverse('Songs:detail', kwargs={'pk': self.kwargs['pk']})

class EditReviewView(LoginRequiredMixin, UpdateView):
    model = SongRating
    template_name = 'songs/song_rate_view.html'
    form_class = EditReviewForm

    def get_success_url(self):
        # Redirect after a successful submission
        return reverse('Songs:detail', kwargs={'pk': self.object.Song_id})

    def get_object(self, queryset=None):
        # Only get the SongRating object for the current user and song
        # if multiple (shouldn't be but just in case) then get the first one
        obj = SongRating.objects.filter(Song_id=self.kwargs['pk'], creator=self.request.user).first()
        return obj
    
    #context for auto populating the form rating and comment
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rating'] = self.object.rating
        context['comment'] = self.object.comment
        return context
    
class DeleteReviewView(LoginRequiredMixin, DeleteView):
    model = SongRating
    template_name = 'songs/song_delete_review.html'

    def get_success_url(self):
        # Redirect after a successful submission
        return reverse('Songs:detail', kwargs={'pk': self.object.Song_id})

    def get_object(self, queryset=None):
        # Only get the SongRating object for the current user and song
        # if multiple (shouldn't be but just in case) then get the first one
        obj = SongRating.objects.filter(Song_id=self.kwargs['pk'], creator=self.request.user).first()
        return obj
    
def delete_review(request, pk):
    review = SongRating.objects.get(id=pk)
    if request.method == "POST":
        review.delete()
        return redirect('Songs:detail', pk=review.Song_id)
    context = {'review': review}
    return render(request, 'songs/song_delete_review.html', context)

class SongDeleteView(UserPassesTestMixin, DeleteView):
    model = Song
    success_url = reverse_lazy('Songs:list')

    def test_func(self):
        return self.request.user.is_superuser

class SongCreateView(CreateView):
    model = Song
    fields = ['spotify_song_id']
    template_name = 'Songs/Song_create_view.html'
    success_url = reverse_lazy('Songs:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['spotify_access_token'] = self.request.session.get('spotify_access_token', '')
        return context

def song_reviews(request, pk):
    reviews_query = SongRating.objects.filter(Song_id=pk).values(
        'id', 'rating', 'comment', 'creator__username', 'Song'
    )

    reviews = list(reviews_query)
    if request.user.is_authenticated:
        user_review = next((r for r in reviews if r['creator__username'] == request.user.username), None)
        if user_review:
            reviews.remove(user_review)
            reviews.insert(0, user_review)

    return JsonResponse(reviews, safe=False)

def user_reviews(request, pk):
    reviews_query = SongRating.objects.filter(creator_id=pk).values(
        'id', 'rating', 'comment', 'creator__username', 'Song'
    )

    reviews = list(reviews_query)
    if request.user.is_authenticated:
        user_review = next((r for r in reviews if r['creator__username'] == request.user.username), None)
        if user_review:
            reviews.remove(user_review)
            reviews.insert(0, user_review)

    return JsonResponse(reviews, safe=False)

def get_spotify_song_id(request, pk):
    song = Song.objects.get(id=pk)
    spotify_song_id = song.spotify_song_id
    return JsonResponse({'spotify_song_id': spotify_song_id})

def spotify_auth_redirect(request):
    next_url = request.GET.get('next', settings.DEFAULT_RETURN_URL)
    #prepend "Songs:" to the next_url
    next_url = "Songs:" + next_url
    full_next_url = request.build_absolute_uri(reverse(next_url))

    params = {
        'client_id': settings.SPOTIFY_CLIENT_ID,
        'response_type': 'code',
        'redirect_uri': settings.SPOTIFY_REDIRECT_URI,
        'scope': 'user-read-private',
        'state': next_url,  # Use state parameter to pass the next_url
    }
    url = f'https://accounts.spotify.com/authorize?{urlencode(params)}'
    return redirect(url)

def spotify_callback(request):
    code = request.GET.get('code')
    error = request.GET.get('error')
    next_url = request.GET.get('state', settings.DEFAULT_RETURN_URL)
    #next_url = "Songs:" + next_url

    if error:
        # Handle the scenario where the user denied the request or some other error occurred.
        return HttpResponseRedirect(reverse('error_view_name'))  # Redirect to an error page or similar.

    if code:
        # Exchange the code for an access token
        response = requests.post('https://accounts.spotify.com/api/token', data={
            'grant_type': 'authorization_code',
            'code': code,
            'redirect_uri': settings.SPOTIFY_REDIRECT_URI,
            'client_id': settings.SPOTIFY_CLIENT_ID,
            'client_secret': settings.SPOTIFY_CLIENT_SECRET,
        })

        if response.status_code == 200:
            data = response.json()
            access_token = data['access_token']
            # Optionally handle refresh_token and save them for later use.
            request.session['spotify_access_token'] = access_token  # Save the access token in the session or user's profile

            # Ensure the next_url is safe to redirect to
            #if not is_safe_url(url=next_url, allowed_hosts={request.get_host()}):
            #    return HttpResponseRedirect(reverse('Songs:list'))  # Redirect to a safe default page

            return HttpResponseRedirect(reverse(next_url))
        else:
            # Handle failure in obtaining an access token.
            return HttpResponseRedirect(reverse('error_view_name'))  # Redirect to an error page or similar.

    # Handle scenarios where there's neither code nor error.
    return HttpResponseRedirect(reverse('default_view_name'))  # Redirect to a default page or an error page.

@csrf_exempt  # Consider using CSRF protection for production
@require_POST
def save_song(request):
    data = json.loads(request.body)
    spotify_song_id = data.get('spotify_song_id')

    if spotify_song_id:
        # Create and save the new song
        song = Song(spotify_song_id=spotify_song_id)
        song.save()
        return JsonResponse({'status': 'success', 'message': 'Song added successfully'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid data'}, status=400)

musicreview/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_id'] = self.object.id  # Add the user's ID to the context
        return context



user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
        "bio"
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

musicreview/templates/songs/song_confirm_delete.html
{% extends "base.html" %}
{% block title %}Song Confirm Delete{% endblock title %}
{% block content %}
<h2>Are you sure you want to delete {{ Song.name }}?</h2>
<form method="post">
{% csrf_token %}
<button value="Confirm" class="btn btn-danger" type="submit">Delete</button>
<a class="btn btn-secondary" href="{% url 'Songs:list' %}">Cancel</a>
</form>
{% endblock content %}

musicreview/templates/songs/song_create_view.html
{% extends "base.html" %}
{% block content %}
{% block title %}Song Create{% endblock title %}
<div id="toast"></div>

<style>
    /* Toast Styling */
    #toast {
        visibility: hidden;
        min-width: 250px;
        margin-left: -125px;
        background-color: #333;
        color: #fff;
        text-align: center;
        border-radius: 2px;
        padding: 16px;
        position: fixed;
        z-index: 1;
        left: 50%;
        bottom: 30px;
        font-size: 17px;
    }

    #toast.show {
        visibility: visible;
        -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;
        animation: fadein 0.5s, fadeout 0.5s 2.5s;
    }

    @-webkit-keyframes fadein {
        from {bottom: 0; opacity: 0;} 
        to {bottom: 30px; opacity: 1;}
    }

    @keyframes fadein {
        from {bottom: 0; opacity: 0;}
        to {bottom: 30px; opacity: 1;}
    }

    @-webkit-keyframes fadeout {
        from {bottom: 30px; opacity: 1;} 
        to {bottom: 0; opacity: 0;}
    }

    @keyframes fadeout {
        from {bottom: 30px; opacity: 1;}
        to {bottom: 0; opacity: 0;}
    }
</style>

<input type="text" id="song-search-box" placeholder="Search for a song" oninput="searchSongs()">

<div id="song-results"></div>

<script>
    const accessToken = '{{ spotify_access_token }}';

    async function searchSongs() {
        let searchQuery = document.getElementById('song-search-box').value;
        let resultsDiv = document.getElementById('song-results');

        if (searchQuery.length < 3) {
            resultsDiv.innerHTML = '';
            return; // Avoid searching for too short strings
        }

        let response = await fetch(`https://api.spotify.com/v1/search?q=${encodeURIComponent(searchQuery)}&type=track`, {
            headers: {
                'Authorization': `Bearer ${accessToken}`
            }
        });

        let data = await response.json();
        resultsDiv.innerHTML = '';

        data.tracks.items.forEach(track => {
            let card = document.createElement('div');
            card.className = 'song-card';
            card.innerHTML = `
                <p>Song: ${track.name}</p>
                <p>Artist: ${track.artists[0].name}</p>
                <button onclick="addSong('${track.id}')">Add Song</button>
            `;
            resultsDiv.appendChild(card);
        });
    }

    async function addSong(spotifySongId) {
    let response = await fetch('/Songs/save/', {
        method: 'POST',
        headers: {
            'X-CSRFToken': getCookie('csrftoken'),
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({spotify_song_id: spotifySongId})
    });

    if (response.ok) {
        window.location.href = '/Songs/'; // Redirect to the song view
    } else {
        const errorData = await response;
        try {
            //show toast with django html content
            showToast(await errorData.text());
        } catch (error) {
            showToast('Error adding song'); // Fallback error message
        }
    }
    }

    function showToast(message) {
        // Assuming you have a toast element in your HTML
        let toast = document.getElementById("toast");
        toast.innerText = message;
        toast.className = "show";
        setTimeout(() => { toast.className = toast.className.replace("show", ""); }, 3000);
    }


    // Function to get CSRF token from cookies
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>

<style>
.song-card {
    border: 1px solid #ddd;
    padding: 10px;
    margin-bottom: 10px;
}
</style>

{% endblock content %}

musicreview/templates/songs/song_delete_review.html
{% extends "base.html" %}

{% block title %}Song Confirm Delete{% endblock title %}

{% block content %}
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete this review?</p>
    <form method="post">
        {% csrf_token %}
        <button value="Confirm" class="btn btn-danger" type="submit">Delete</button>
        <a class="btn btn-secondary" href="{% url 'Songs:list' %}">Cancel</a>
    </form>
{% endblock content %}

musicreview/templates/songs/song_list.html
{% extends "base.html" %}
{% block title %}Song List{% endblock title %}
{% block content %}
<h2>Song List</h2>
<table class="table" id="songs-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Album</th>
            <th>Artist</th>
            <th>Genres</th>
            <th>Popularity</th>
            <th>Duration</th>
            <th>Rating</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody id="song-list">
        <!-- Songs will be populated here by JavaScript -->
    </tbody>
</table>

<a class="btn btn-primary" href="{% url 'Songs:spotify-auth-redirect' %}?next=create">Add Song</a>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>
    const songs = {{ songs | safe }};
    console.log(songs)
    const accessToken = '{{ request.session.spotify_access_token }}';

    songs.forEach((song) => {
        $.ajax({
            url: `https://api.spotify.com/v1/tracks/${song.spotify_song_id}`,
            headers: {
                'Authorization': `Bearer ${accessToken}`
            },
            success: function(songData) {
                let userHasReviewedJs = song.user_has_reviewed;
                addSongToTable(songData, song.id, song.average_rating, userHasReviewedJs);
            },
            error: function(xhr) {
                if (xhr.status === 401 || xhr.status === 400) {
                    window.location.href = `/Songs/spotify-auth-redirect?next=list`;
                } else {
                    console.error('Error fetching song data:', xhr.status);
                }
            }
        });
    });

    function fetchGenres(artistId) {
        return $.ajax({
            url: `https://api.spotify.com/v1/artists/${artistId}`,
            headers: {
                'Authorization': `Bearer ${accessToken}`
            },
            error: function(xhr) {
                console.error('Error fetching artist genres:', xhr.status);
                return 'Unknown';
            }
        });
    }

    async function addSongToTable(songData, dbId, avg_review, userHasReviewedStr) {
        console.log(songData)
        console.log(userHasReviewedStr)
        var userHasReviewed = userHasReviewedStr === 'True';
        let table = document.getElementById('song-list');
        let row = table.insertRow();
        var hasLoggedIn = '{{ request.user.is_authenticated }}';

        let nameCell = row.insertCell(0);
        let albumCell = row.insertCell(1);
        let artistCell = row.insertCell(2);
        let genresCell = row.insertCell(3);
        let popularityCell = row.insertCell(4);
        let durationCell = row.insertCell(5);
        let ratingCell = row.insertCell(6);
        let actionsCell = row.insertCell(7);

        nameCell.innerHTML = `<a href="{% url 'Songs:detail' 1234 %}">${songData.name}</a>`.replace('1234/', dbId);
        albumCell.innerHTML = songData.album.name;
        artistCell.innerHTML = songData.artists.map(artist => artist.name).join(', ');

        if (songData.artists.length > 0) {
            fetchGenres(songData.artists[0].id).done(function(genres) {
                
                genresCell.innerHTML = genres.genres.join(', ');
            }).fail(function() {
                genresCell.innerHTML = 'Unknown';
            });
        } else {
            genresCell.innerHTML = 'Unknown';
        }

        console.log(hasLoggedIn);
        popularityCell.innerHTML = songData.popularity;
        durationCell.innerHTML = formatDuration(songData.duration_ms);
        let remaindingStars = 5 - avg_review;
        console.log("remaindingStars");
        console.log(remaindingStars);
        console.log("avg_review");
        console.log(avg_review);
        ratingCell.innerHTML = '★'.repeat(avg_review) + '☆'.repeat(remaindingStars);  // Placeholder for rating
        let reviewActionHtml;
        if (userHasReviewed) {
            reviewActionHtml = `<a href='edit-review/${dbId}'>Edit Review</a>`;
        } else {
            reviewActionHtml = `<a href='review/${dbId}'>Create Review</a>`;
        }
        if (hasLoggedIn != 'True'){
            reviewActionHtml = `<a href="/accounts/login">Login to Review</a>`;
        }

        actionsCell.innerHTML = `${reviewActionHtml} {% if request.user.is_superuser %}| <a href='delete/${dbId}/'>Delete</a>{% endif %}`;
    }

    function formatDuration(durationMs) {
        let minutes = Math.floor(durationMs / 60000);
        let seconds = ((durationMs % 60000) / 1000).toFixed(0);
        return minutes + ":" + (seconds < 10 ? '0' : '') + seconds;
    }
</script>


{% endblock content %}

musicreview/templates/songs/song_rate_view.html
{% extends "base.html" %}

{% block title %}Song Review{% endblock title %}

{% block content %}
<div class="container">
    <h2>Review Song: {{ song.name }}</h2>
    <form method="post">
        {% csrf_token %}
        <!-- Assuming you have a form named 'review_form' -->
        <!-- accept auto populated form values for edit-->
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Submit Review</button>
    </form>
</div>

<script>
    // check for auto populating context comment and rating
    // if so, auto populate form, otherwise do nothing
    if { {{comment}} } != null {
        document.getElementById("id_comment").value = {{ comment }};
    }
    if { {{rating}} } != null {
        document.getElementById("id_rating").value = {{ rating }};
    }

</script>
{% endblock content %}

musicreview/templates/songs/song_update_view.html
{% extends "base.html" %}
{% block title %}Song List{% endblock title %}
{% block content %}

{% endblock content %}